"""The unique name model of product has been changed False.

Revision ID: 82585da7819c
Revises: aef854e0504f
Create Date: 2026-08-09 19:44:21.173837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82585da7819c'
down_revision = 'aef854e0504f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('product_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('product_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
