"""The model of product has been added

Revision ID: 890a96dff5ec
Revises: 37d9bbeec318
Create Date: 2026-06-14 01:10:41.650651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890a96dff5ec'
down_revision = '37d9bbeec318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
