"""The unique name model of group has been changed False.

Revision ID: aef854e0504f
Revises: e2d56370e10c
Create Date: 2026-08-09 19:41:35.029413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef854e0504f'
down_revision = 'e2d56370e10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('group_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('group_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
